apiVersion: apps/v1
kind: Deployment
metadata:
  name: captcha-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captcha-services
  template:
    metadata:
      labels:
        app: captcha-services
    spec:
      containers:
      - name: python
        image: bennoli13/captcha-services
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-static
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-conf
        hostPath:
          path: ./nginx/conf.d
      - name: nginx-static
        hostPath:
          path: ./nginx/static/static
---
apiVersion: v1
kind: Service
metadata:
  name: captcha-services
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: captcha-services